version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Docker/Dockerfile
    container_name: python_app
    volumes:
      - .:/app
    ports:
      - "5000:80"

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8080:80"
    depends_on:
      - db
